import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
<<<<<<<<< Temporary merge branch 1
import './globals.css'
import { useLinkClickHandler } from 'react-router-dom'
=========
import './globals.css';
import { UserContextProvider } from '../features/user/UserContextProvider';
>>>>>>>>> Temporary merge branch 2

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <UserContextProvider>
      <html lang="en">
        <body className={inter.className}>
          <div>
            {children}
          </div> 
          </body>
      </html>
    </UserContextProvider>
  )
}
