import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserContextProvider } from "../features/user/UserContextProvider";
import HamburgerMenu from "@/components/HamburgerMenu/HamburgerMenu";
import { ReactQueryClientProvider } from "@/features/user/query/QueryClientProvider";
import { ModalContextProvider } from "@/features/modal/ModalContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryClientProvider>
      <UserContextProvider>
        <ModalContextProvider>
          <html lang="en">
            <body className={inter.className}>
              <HamburgerMenu />
              <div>{children}</div>
            </body>
          </html>
        </ModalContextProvider>
      </UserContextProvider>
    </ReactQueryClientProvider>
  );
}
